### ISSUE TITLE
Rocket todo's

### ISSUE THREAD

**Issue by danieledeluca** [danieledeluca/rocket#1]
# Release v1.0.0

Initial release of Rocket!

**Comment by danieledeluca** [comment]
# Release v1.0.1

## CSS

- [x] Add blue color variable to CSS variable
- [x] Add big and small buttons variants
- [x] Remove padding from pagination
- [x] Remove tertiary button variation
- [x] Change order of buttons and forms SCSS variables
- [x] Refactoring

## JavaScript

- [x] Remove smooth scroll script
- [x] Remove jQuery `document ready`
- [x] Change jQuery unnamed functions to arrow functions
- [x] Refactoring

## Docs

- [x] Add big and small buttons examples
- [x] Remove button tertiary section
- [x] Update icons order
- [x] Update cover parallax section

## Misc

- [x] Add Eslint, Stylelint and Prettier

## Dependencies

- [x] Update dependencies and devDependencies
